name: Publish AAB to Google Play (Draft)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to fetch .aab from'
        required: true
        default: 'mods'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Download backpack.aab from release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/myforgecraft/backpack/releases/tags/${{ github.event.inputs.release_tag }}")
          ASSET_ID=$(echo "$RELEASE_DATA" | jq '.assets[] | select(.name=="backpack.aab") | .id')
          curl -L -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/octet-stream" \
            "https://api.github.com/repos/myforgecraft/backpack/releases/assets/$ASSET_ID" \
            -o backpack.aab

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install fastlane
        run: gem install fastlane -NV

      - name: Publish .aab to Google Play (draft status)
        env:
          SUPPLY_JSON_KEY: ${{ secrets.SUPPLY_JSON_KEY }}
        run: |
          echo "$SUPPLY_JSON_KEY" > api-key.json
          fastlane supply \
            --aab backpack.aab \
            --json_key api-key.json \
            --package_name com.Forgecraft.BackPackMod \
            --release_status draft
