name: Publish Ready AAB to Google Play

on:
  workflow_dispatch:  # Запуск вручную

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install fastlane
        run: gem install fastlane -NV

      - name: Publish .aab to Google Play
        env:
          SUPPLY_JSON_KEY: ${{ secrets.SUPPLY_JSON_KEY }}
        run: |
          echo "$SUPPLY_JSON_KEY" > api-key.json
          fastlane supply --aab releases/mods/backpack.aab --json_key api-key.json --package_name com.Forgecraft.BackPackMod
