name: Publish AAB from Release to Google Play

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to fetch .aab from'
        required: true
        default: 'mods'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download backpack.aab from release
        uses: dsaltares/fetch-gh-release-asset@v1
        with:
          repo: myforgecraft/backpack
          tag: ${{ github.event.inputs.release_tag }}
          file: backpack.aab
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install fastlane
        run: gem install fastlane -NV

      - name: Publish .aab to Google Play
        env:
          SUPPLY_JSON_KEY: ${{ secrets.SUPPLY_JSON_KEY }}
        run: |
          echo "$SUPPLY_JSON_KEY" > api-key.json
          fastlane supply --aab backpack.aab --json_key api-key.json --package_name com.Forgecraft.BackPackMod
